# Generated by Django 4.2.5 on 2023-10-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='domain',
        ),
        migrations.AlterField(
            model_name='productview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
