# Generated by Django 4.2.5 on 2023-10-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productview_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
