# Generated by Django 4.2.5 on 2023-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='domain',
            field=models.CharField(default='domain name', max_length=255, unique=True),
        ),
    ]
