# Generated by Django 4.2.5 on 2023-10-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productview_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
