# Generated by Django 4.2.5 on 2023-10-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default='No brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
    ]
