# Generated by Django 4.2.5 on 2023-10-26 08:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
