# Generated by Django 4.2.5 on 2023-10-04 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=200)),
                ('cus_email', models.EmailField(max_length=300)),
                ('cus_phone', models.CharField(max_length=40)),
                ('cus_address', models.CharField(max_length=400)),
                ('total_amount', models.PositiveIntegerField()),
                ('transection_id', models.CharField(max_length=100, unique=True)),
                ('num_of_item', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0)),
                ('category', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('quanity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('On The Way', 'On The Way'), ('Deliverd', 'Deliverd')], default='pending', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('pay_system', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('orderd_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.orderitem')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
