# Generated by Django 4.2.5 on 2023-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_info',
            old_name='grand_total',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='payment_method',
            field=models.CharField(choices=[('Cash On', 'Cash On'), ('Bkash', 'Bkash')], default='Cash On', max_length=100),
        ),
    ]
