# Generated by Django 4.2.5 on 2023-10-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_delivery_info_user_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='cart_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
