# Generated by Django 4.2.5 on 2023-10-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_delivery_info_orderd_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_info',
            name='orderd_product',
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='orderd_products',
            field=models.ManyToManyField(to='payment.orderitem'),
        ),
    ]
