# Generated by Django 4.2.5 on 2023-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_grand_total_delivery_info_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_info',
            name='payment_method',
            field=models.CharField(default='Cash On', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery_info',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
