# Generated by Django 4.2.5 on 2023-10-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_delivery_info_orderd_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
