# Generated by Django 4.2.5 on 2023-10-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_delivery_info_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='transaction_number',
            field=models.CharField(default='01', max_length=20),
        ),
    ]
