# Generated by Django 4.2.5 on 2023-10-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delivery_info_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
