# Generated by Django 4.2.5 on 2023-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prices',
            field=models.FloatField(default=0.0),
        ),
    ]
