# Generated by Django 4.2.5 on 2023-10-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prices',
        ),
    ]
